version: "3.8"
services:
  agent:
    container_name: agent
    image: jenkins/ssh-agent:latest-jdk11
    privileged: true
    user: root
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    networks:
      - jenkins
    expose:
      - 22

  docker:
    container_name: docker
    image: docker:dind
    privileged: true
    command: --storage-driver=overlay2
    networks:
      - jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"

  jenkins:
    container_name: jenkins
    build:
      context: .
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_PASSWORD=${GITHUB_PASSWORD}
        - JENKINS_ADMIN_EMAIL=${JENKINS_ADMIN_EMAIL}
        - JENKINS_ADMIN_DESCRIPTION=${JENKINS_ADMIN_DESCRIPTION}
        - JENKINS_ADMIN_NAME=${JENKINS_ADMIN_NAME}
        - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
        - JENKINS_ADMIN_USER=${JENKINS_ADMIN_USER}
        - JENKINS_URL=${JENKINS_URL}
    restart: on-failure
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home

volumes:
  jenkins-docker-certs: {}
  jenkins-data: {}

networks:
  jenkins: {}